[general]
board = "mega2560"

open-console = true
serial-baudrate = 115200

# For documentation about this file, check here:
# https://github.com/Rahix/avr-hal/blob/main/ravedude/README.md#ravedudetoml-format
